apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"hi-dev-service","namespace":"dev"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":8080}],"selector":{"app":"hi-dev"},"type":"ClusterIP"}}
    creationTimestamp: "2025-10-23T12:23:34Z"
    name: hi-dev-service
    namespace: dev
    resourceVersion: "135477"
    uid: f4fb1100-7e52-461f-af61-e3e2e18f9659
  spec:
    clusterIP: 10.111.22.58
    clusterIPs:
    - 10.111.22.58
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: hi-dev
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2025-10-23T12:23:34Z","name":"nginx-service","namespace":"dev","resourceVersion":"135477","uid":"f4fb1100-7e52-461f-af61-e3e2e18f9659"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":8080}],"selector":{"app":"nginx"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
    creationTimestamp: "2025-10-25T07:39:03Z"
    name: nginx-service
    namespace: dev
    resourceVersion: "157047"
    uid: a53b22d8-34d3-48aa-a489-c5bf48424188
  spec:
    clusterIP: 10.110.51.64
    clusterIPs:
    - 10.110.51.64
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: nginx
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
