apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: dev
data:
  index.html: |
    <!DOCTYPE html>
    <html><body>
    <h1 style="color: blue;">صفحه اصلی (Root)</h1>
    <p>اینجا <code>/</code> است.</p>
    </body></html>

  nginx-index.html: |
    <!DOCTYPE html>
    <html><body>
    <h1 style="color: green;">صفحه /nginx</h1>
    <p>اینجا <code>/nginx</code> است.</p>
    </body></html>

  nginx-green-index.html: |
    <!DOCTYPE html>
    <html><body>
    <h1 style="color: lime;">صفحه /nginx/green</h1>
    <p>اینجا <code>/nginx/green</code> است.</p>
    </body></html>
---
# --- جداکننده برای volume projection
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-structured
  namespace: dev
  labels:
    app: nginx-html-structured
data: {}
items:
  - key: index.html
    path: index.html
  - key: nginx-index.html
    path: nginx/index.html
  - key: nginx-green-index.html
    path: nginx/green/index.html