apiVersion: apps/v1
kind: Deployment
metadata:
  name: hi-dev-deployment
  namespace: dev
  labels:
    app: hi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hi-dev
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: hi-dev
    spec:
      containers:
        - name: hi-dev
          image: sabzali/devops-api:2025.11.07-21
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "100m"        # 0.1 CPU requested
              memory: "128Mi"    # base memory reservation
            limits:
              cpu: "500m"        # max 0.5 CPU per pod
              memory: "256Mi"    # cap memory usage
