apiVersion: apps/v1
kind: Deployment
metadata:
  name: hi-dev-deployment
  namespace: dev
  labels:
    app: hi-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hi-dev
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: hi-dev
    spec:
      containers:
        - name: hi-dev
          image: sabzali/devops-api:2025.11.01-19
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP