apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hi-dev-ingress
  namespace: dev
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /$2
#    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # 1. Root → hi-dev-service
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hi-dev-service
                port:
                  number: 80

          # 2. /nginx/* → nginx-service, strip /nginx, use REGEX
          - path: /nginx
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80