apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hi-dev-ingress
  namespace: stg
spec:
  ingressClassName: nginx
  rules:
    - host: hi-stg.example.com   # ðŸ‘ˆ unique host
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hi-dev-service
                port:
                  number: 80
