apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"hi-dev"},"name":"hi-dev-deployment","namespace":"dev"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"hi-dev"}},"template":{"metadata":{"labels":{"app":"hi-dev"}},"spec":{"containers":[{"image":"sabzali/devops-api:2025.10.23-14","name":"hi-dev","ports":[{"containerPort":8080}]}]}}}}
    creationTimestamp: "2025-10-23T12:21:57Z"
    generation: 2
    labels:
      app: hi-dev
    name: hi-dev-deployment
    namespace: dev
    resourceVersion: "175070"
    uid: 1de8569f-0a86-4c1c-a6fd-cfbe4f9f20b3
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: hi-dev
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: hi-dev
      spec:
        containers:
        - image: sabzali/devops-api:2025.10.23-14
          imagePullPolicy: IfNotPresent
          name: hi-dev
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 2
    conditions:
    - lastTransitionTime: "2025-10-23T12:21:58Z"
      lastUpdateTime: "2025-10-23T12:31:17Z"
      message: ReplicaSet "hi-dev-deployment-5965b8947c" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2025-10-26T07:23:06Z"
      lastUpdateTime: "2025-10-26T07:23:06Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 2
    readyReplicas: 2
    replicas: 2
    updatedReplicas: 2
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2025-10-13T06:43:06Z","generation":4,"labels":{"app":"nginx"},"name":"nginx-deployment","namespace":"dev","resourceVersion":"151658","uid":"f4f62435-4ebd-4c5a-977d-8c18cfef0eb4"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"nginx"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"docker.arvancloud.ir/nginx","imagePullPolicy":"Always","name":"nginx","ports":[{"containerPort":80,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2025-10-13T06:43:07Z","lastUpdateTime":"2025-10-13T07:01:03Z","message":"ReplicaSet \"nginx-deployment-697457668\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2025-10-25T06:25:33Z","lastUpdateTime":"2025-10-25T06:25:33Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":4,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
    creationTimestamp: "2025-10-25T06:35:54Z"
    generation: 4
    labels:
      app: nginx
    name: nginx-deployment
    namespace: dev
    resourceVersion: "175128"
    uid: bf3a57a7-6126-4fff-8aaf-67213730b587
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: nginx
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: nginx
      spec:
        containers:
        - image: docker.arvancloud.ir/nginx
          imagePullPolicy: Always
          name: nginx
          ports:
          - containerPort: 80
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 2
    conditions:
    - lastTransitionTime: "2025-10-25T06:35:54Z"
      lastUpdateTime: "2025-10-25T06:36:01Z"
      message: ReplicaSet "nginx-deployment-697457668" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2025-10-26T07:23:11Z"
      lastUpdateTime: "2025-10-26T07:23:11Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 4
    readyReplicas: 2
    replicas: 2
    updatedReplicas: 2
kind: List
metadata:
  resourceVersion: ""
